scrape_configs:
  - job_name: 'doceasy-worker'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['doceasy-worker:8282'] # Como a minha aplicação não está no container, eu tenho que colocar o IP da minha máquina para que o Prometheus consiga baixar coisas da minha aplicação.
        labels:
          application: 'doceasy-worker'
      - targets: ['doceasy-middler:8081'] # Como a minha aplicação não está no container, eu tenho que colocar o IP da minha máquina para que o Prometheus consiga baixar coisas da minha aplicação.
        labels:
          application: 'doceasy-middler'
      - targets: ['metamorphic-pdf:8080'] # Como a minha aplicação não está no container, eu tenho que colocar o IP da minha máquina para que o Prometheus consiga baixar coisas da minha aplicação.
        labels:
          application: 'metamorphic-pdf'